name: 'Deploy an OpenAI Model to Azure action'
description: 'This action helps create an OpenAI search model'
branding:
  icon: 'play-circle'
  color: 'blue'
inputs:
  client-id:
    description: 'Client id to log in to azure'
    required: true
  tenant-id:
    description: 'Tenant id to log in to azure'
    required: true
  subscription-id:
    description: 'Subscription id to be used with your az login'
    required: true
  location:
    description: 'Location to deploy resources to'
    required: true
  openai-location:
    description: 'Location to deploy OpenAI resources to'
    required: true
  principal-id:
    description: 'FIC Service Principal ID'
    required: true
  env-name:
    description: 'Name of environment where env values are set'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Checkout master'
      uses: actions/checkout@v3

    - name: 'az cli login'
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        enable-AzPSSession: true
          
    - name: 'Install azd'
      uses: Azure/setup-azd@v0.1.0

    - name: 'Install Nodejs'
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 'Create directory'
      run: mkdir airepo
      shell: pwsh

    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: vaibbavisk20/vskAOAISearchDemo
        path: airepo

    - name: 'Update bot_config.yaml'
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'airepo/AOAISearchDemo/app/backend/bot_config.yaml'
        commitChange: false
        changes: |
          {
            "approach_classifier.openai_settings.engine": "classifier",
            "structured_query_nl_to_sql.openai_settings.engine": "chat",
            "structured_query_nl_to_sql.model_params.model_name": "gpt-4",
            "structured_final_answer_generation.openai_settings.engine": "chat",
            "unstructured_search_query_generation.openai_settings.engine": "chat",
            "unstructured_final_answer_generation.openai_settings.engine": "chat",
            "unstructured_final_answer_generation.model_params.model_name": "gpt-4",
            "embeddings.openai_settings.engine": "embeddings"
          }

    - name: 'Update azure.yaml to skip Connect-AzAccount step'
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'airepo/AOAISearchDemo/azure.yaml'
        commitChange: false
        changes: |
          {
            "hooks.preprovision.run": "Install-Module AzureAD -Force;Get-AzContext"
          }

    - name: Install ODBC Driver for SQL Server v18
      uses: Yarden-zamir/install-mssql-odbc@v1.0.2

    
    - name: Az powershell
      uses: azure/powershell@v2
      with:
        inlineScript: |
          azd auth login --client-id ${{ inputs.client-id }} --federated-credential-provider "github" --tenant-id ${{ inputs.tenant-id }}
          cd airepo/AOAISearchDemo
          Get-AzAccessToken -ResourceUrl "https://vault.azure.net"
          azd env new ${{ inputs.env-name }}
          azd env set AZURE_ENV_NAME "${{ inputs.env-name }}"
          azd env set AZURE_LOCATION ${{ inputs.location }}
          azd env set AZURE_OPENAI_LOCATION ${{ inputs.openai-location }}
          azd env set AZURE_SUBSCRIPTION_ID ${{ inputs.subscription-id }}
          azd env set AZURE_PRINCIPAL_ID ${{ inputs.principal-id }}
          Get-AzContext -ListAvailable
          azd up --no-prompt -e ${{ inputs.env-name }}
        azPSVersion: "latest"