name: 'Azure Infrastructure for Open AI powered Chat'
description: 'This action helps deploy Infrastructure to Azure that helps achieve a chat-completion experience powered by Open AI'
branding:
  icon: 'play-circle'
  color: 'blue'
inputs:
  client-id:
    description: 'Client id to log in to azure'
    required: true
  tenant-id:
    description: 'Tenant id to log in to azure'
    required: true
  subscription-id:
    description: 'Subscription id to be used with your az login'
    required: true
  location:
    description: 'Location to deploy resources to'
    required: true
  openai-location:
    description: 'Location to deploy OpenAI resources to'
    required: true
  principal-id:
    description: 'FIC Service Principal ID'
    required: true
  env-name:
    description: 'Name of environment where env values are set'
    required: true
  principal-name:
    description: 'FIC Service Principal Name'
    required: true
  documentintelligence-location:
    decsription: 'Location to deploy Document Intelligence resources to'
    required: true
  bring-your-own-data:
    description: 'Boolean to indicate if you are bringing your own data'
    required: false
  data-path:
    description: 'Path to data to be used to train the OpenAI model'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Checkout master'
      uses: actions/checkout@v3

    - name: 'az cli login'
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        enable-AzPSSession: true
          
    - name: 'Install azd'
      uses: Azure/setup-azd@v0.1.0

    - name: 'Install Nodejs'
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 'Create directory'
      run: mkdir airepo
      shell: pwsh

    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: vaibbavisk20/vsk-search-openai-demo-py
        path: airepo

    - name: Az powershell
      uses: azure/powershell@v2
      with:
        inlineScript: |
          cd airepo
          dir
          azd auth login --client-id ${{ inputs.client-id }} --federated-credential-provider "github" --tenant-id ${{ inputs.tenant-id }}
          Get-AzAccessToken -ResourceUrl "https://vault.azure.net"
          azd env new ${{ inputs.env-name }}
          azd env set AZURE_ENV_NAME ${{ inputs.env-name }}
          azd env set AZURE_LOCATION ${{ inputs.location }}
          azd env set AZURE_SUBSCRIPTION_ID ${{ inputs.subscription-id }}
          azd env set AZURE_PRINCIPAL_ID ${{ inputs.principal-id }}
          azd env set AZURE_PRINCIPAL_NAME ${{ inputs.principal-name }}  
          azd env set AZURE_OPENAI_LOCATION ${{ inputs.openai-location }}
          azd env set AZURE_DOCUMENTINTELLIGENCE_LOCATION ${{ inputs.documentintelligence-location }}
          azd env set BRING_YOUR_OWN_DATA ${{ inputs.bring-your-own-data }}
          azd env set CUSTOM_DATA_PATH ${{ inputs.data-path }}
          Get-AzContext -ListAvailable
          azd env get-values
          azd up --no-prompt -e ${{ inputs.env-name }}
        azPSVersion: "latest"
