name: Workflow to deploy OpenAI resource to Azure

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  deploy-resources-to-azure:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
    steps:
        - name: Checkout master
          uses: actions/checkout@v3
          
        - name: Deploy a Open AI action
          uses: ./.github/actions/ai_deploy
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
            resource-group-name: ${{ vars.AZURE_RG }}
            applicationPassword: ${{ secrets.APP_PASSWORD }}
            location: 'eastus'
