name: Workflow to deploy OpenAI infrastructure to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  deploy-resources-to-azure:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
    steps:
        - name: Checkout master
          uses: actions/checkout@v3
          
        - name: Deploy Open AI infrastructure action execution
          uses: ./
          with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              principal-id: ${{ secrets.AZURE_APP_ID }}
              subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
              location: ${{ vars.AZURE_LOCATION }}
              env-name: ${{ vars.AZURE_ENV_NAME }}
              principal-name: ${{ secrets.AZURE_APP_NAME }}
              openai-location: ${{ vars.AZURE_OPENAI_LOCATION }}
              documentintelligence-location: ${{ vars.AZURE_DOCUMENTINTELLIGENCE_LOCATION }}
              bring-your-own-data: true
              data-path: "mydata"
